In [2]:
#Q1 Python basics
p=int(input("Principle: "))
t=int(input("Time: "))
r=int(input("Rate"))
a=p*(1+r/100)*t
ci=a-p
print(ci)

Principle: 100
Time: 2
Rate10
120.00000000000003


In [4]:
#Q2 Python basics
n=int(input("enter size"))
l=list()
for i in range(n):
  l.append(input())
p=list()
for i in range(n):
  per=(l.count(l[i])/n)*100
  p.append(per)
print(p)

enter size5
he
hi
he
hi
hi
[40.0, 60.0, 40.0, 60.0, 60.0]


5 ==> 1,0,1 
4 ==> 100
3 ==> 11
6 ==> 110

In [13]:
#Q3 Python basics
n=int(input("Enter"))
x=list()
while(n!=0):
  x.append(n%2)
  n=int(n/2)
y=x[::-1]
if(y==y[::-1]):
  print("True")
else:
  print("False")

Enter6
False


In [18]:
#Q4 Python basics
n=int(input("Enter"))
x=list(map(int,str(n)))
flag=0
for i in x:
  if(int(i)!=0 and n%int(i)!=0):
    flag=1
    break
if(flag==1):
  print("No")
else:
  print("Yes")

Enter346
No


In [19]:
#Q5 Python basics
n=int(input("Enter"))
x=list()
for i in range(n):
  x.append(int(input()))
x.sort()
print(x[n-2])

Enter5
1
2
3
5
4
4


In [1]:
#Q1 Numpy basics
import random
out=list()
for i in range(4):
  in1=list()
  for j in range(5):
    in2=list()
    for k in range(2):
      in2.append(random.randrange(1,10))
    in1.append(in2)
  out.append(in1)
out

[[[9, 3], [9, 4], [4, 1], [9, 7], [3, 6]],
 [[4, 7], [7, 4], [1, 7], [3, 3], [4, 1]],
 [[8, 1], [8, 7], [1, 7], [2, 4], [5, 4]],
 [[9, 2], [3, 8], [9, 2], [9, 7], [4, 9]]]

In [24]:
#Q2 Numpy basics
from numpy import random
n=int(input("Enter"))
x=random.randint(100,size=(n))
out=list()
in1=list()
for i in range(int(n/2)):
  in1.append(x[i])
out.append(in1)
in1=list()
for j in range(i,n):
  in1.append(x[j])
out.append(in1)
out

Enter10


[[45, 40, 49, 44, 55], [55, 14, 48, 16, 50, 26]]

In [2]:
#Q3 Numpy basics
import numpy as np
x=np.array([34,1,4,8,15])
for i in range(len(x)):
  x[i]=(x[i]*(9/5))+32
x

array([93, 33, 39, 46, 59])

In [7]:
#Q4 Numpy basics
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Number of dimensions: ",x.ndim)
print("Number of elements: ",x.size)
print("Number of bytes: ",x.itemsize)
#x.shape

Number of dimensions:  2
Number of elements:  12
Number of bytes:  8


(3, 4)

In [9]:
#Q5 Numpy basics
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
print(x[0][1],x[0][2])
print(x[1][1],x[1][2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2 3
6 7


In [11]:
new_array = np.random.randint(10, size=(4,5,2))
new_array

array([[[8, 6],
        [4, 0],
        [5, 1],
        [8, 8],
        [6, 7]],

       [[7, 4],
        [1, 3],
        [9, 7],
        [4, 8],
        [7, 2]],

       [[7, 1],
        [9, 1],
        [0, 9],
        [7, 2],
        [8, 5]],

       [[1, 3],
        [6, 6],
        [8, 6],
        [0, 0],
        [8, 3]]])